title: jung hyunsung
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sms6874.github.io"
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: jung hyunsung
tagline: FRIEND
about-description: Let me introduce my friend # Add Discription   
pic: 정현성.jpg # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: sms6974@naver.com # Add your Email address
phone: 010-1234-5678 # Add your Phone number
website:  # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: sms6974 # Add your Github handle
instagram:
  - seo_.03_22 # Add your Twitter handle
  - hyunsung2326 # Add your Twitter handle
  - kangjimin823 # Add your Twitter handle

# Tracker
analytics: 

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
